name: build

on: [push]

jobs: 
  build_check:
    name: build check
    runs-on: windows-latest
    steps:
      - name: setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: setup v
        run: |
          cd ..
          git clone https://github.com/vlang/v.git --depth 1 v
          cd v
          ./make.bat
          ./v.exe symlink -githubci
      - name: checkout
        uses: actions/checkout@v2
      - name: setup build
        run: |
          mkdir build
      - name: build prod
        run: nmake ci-build-prod
      - name: build debug
        run: nmake ci-build-debug
